"""Render the zccache vs sccache feature comparison matrix.

Single source of truth: `docs/feature-matrix.yaml`.

Writes three rendered outputs:
  1. README.md headline table between
        <!-- BEGIN feature-matrix-headline --> / <!-- END feature-matrix-headline -->
     markers (only rows with `headline: true`).
  2. README.md full table between
        <!-- BEGIN feature-matrix-full --> / <!-- END feature-matrix-full -->
     markers (all rows, grouped by category).
  3. `docs/FEATURE-MATRIX.md` — regenerated whole, with extra `notes` and
     `evidence` columns.

Invoke via:

    uv run --with pyyaml python ci/render_feature_matrix.py
    uv run --with pyyaml python ci/render_feature_matrix.py --check

`--check` renders to in-memory buffers and exits non-zero if any output is
stale relative to the YAML. This is the CI gate that fires when the YAML is
edited without re-rendering.

PyYAML is loaded via `uv --with` so we do not need to add it to the project's
runtime dependencies — this script lives in the CI/docs carve-out.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

try:
    import yaml
except ImportError:  # pragma: no cover - exercised only without `uv --with`
    sys.stderr.write(
        "ERROR: PyYAML is not available. Invoke this script via:\n"
        "  uv run --with pyyaml python ci/render_feature_matrix.py\n"
    )
    sys.exit(2)


REPO_ROOT = Path(__file__).resolve().parents[1]
YAML_PATH = REPO_ROOT / "docs" / "feature-matrix.yaml"
README_PATH = REPO_ROOT / "README.md"
FEATURE_MATRIX_PATH = REPO_ROOT / "docs" / "FEATURE-MATRIX.md"

HEADLINE_BEGIN = "<!-- BEGIN feature-matrix-headline -->"
HEADLINE_END = "<!-- END feature-matrix-headline -->"
FULL_BEGIN = "<!-- BEGIN feature-matrix-full -->"
FULL_END = "<!-- END feature-matrix-full -->"

GENERATED_BANNER = (
    "<!-- This file is generated by ci/render_feature_matrix.py from "
    "docs/feature-matrix.yaml. Do not edit by hand. -->"
)

VALID_VALUES = {"yes", "no", "partial"}
VALUE_DISPLAY = {
    "yes": "yes",
    "no": "no",
    "partial": "partial",
}

# YAML 1.1 (PyYAML default) parses bare `yes`/`no` as booleans. Accept those
# too and coerce to our canonical strings — keeps the YAML readable without
# requiring per-row quoting.
_BOOL_COERCE = {True: "yes", False: "no"}


def _coerce_support(value: object) -> object:
    if isinstance(value, bool):
        return _BOOL_COERCE[value]
    return value

# Category order in the rendered tables. Extra categories that appear in the
# YAML but not in this list are appended in YAML order at the end.
CATEGORY_ORDER = [
    "Caching scope",
    "Tool coverage",
    "Build system integration",
    "Architecture",
    "Worktree / multi-checkout",
    "Storage backends",
    "Platform / packaging",
    "Performance posture",
]


# ---------------------------------------------------------------------------
# Data loading and validation
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Row:
    id: str
    category: str
    feature: str
    zccache: str
    sccache: str
    headline: bool
    notes: str
    evidence: str


def _require(condition: bool, message: str) -> None:
    if not condition:
        raise SystemExit(f"feature-matrix.yaml: {message}")


def load_rows(path: Path) -> list[Row]:
    """Parse and validate the YAML feature-matrix data."""
    raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    _require(isinstance(raw, list), "top-level YAML must be a list of rows")

    rows: list[Row] = []
    seen_ids: set[str] = set()
    for index, entry in enumerate(raw):
        _require(isinstance(entry, dict), f"row {index}: must be a mapping")
        row_id = entry.get("id")
        _require(isinstance(row_id, str) and bool(row_id), f"row {index}: missing/empty 'id'")
        _require(row_id not in seen_ids, f"row {index}: duplicate id '{row_id}'")
        seen_ids.add(row_id)

        category = entry.get("category")
        feature = entry.get("feature")
        zccache = _coerce_support(entry.get("zccache"))
        sccache = _coerce_support(entry.get("sccache"))

        _require(isinstance(category, str) and bool(category), f"row '{row_id}': missing 'category'")
        _require(isinstance(feature, str) and bool(feature), f"row '{row_id}': missing 'feature'")
        _require(
            isinstance(zccache, str) and zccache in VALID_VALUES,
            f"row '{row_id}': 'zccache' must be one of {sorted(VALID_VALUES)}, got {zccache!r}",
        )
        _require(
            isinstance(sccache, str) and sccache in VALID_VALUES,
            f"row '{row_id}': 'sccache' must be one of {sorted(VALID_VALUES)}, got {sccache!r}",
        )
        assert isinstance(zccache, str)
        assert isinstance(sccache, str)

        headline = bool(entry.get("headline", False))
        notes = entry.get("notes", "") or ""
        evidence = entry.get("evidence", "") or ""
        _require(isinstance(notes, str), f"row '{row_id}': 'notes' must be a string")
        _require(isinstance(evidence, str), f"row '{row_id}': 'evidence' must be a string")

        rows.append(
            Row(
                id=row_id,
                category=category,
                feature=feature,
                zccache=zccache,
                sccache=sccache,
                headline=headline,
                notes=notes.strip(),
                evidence=evidence.strip(),
            )
        )

    _require(len(rows) > 0, "no rows found")
    return rows


# ---------------------------------------------------------------------------
# Rendering helpers
# ---------------------------------------------------------------------------


def _escape_cell(value: str) -> str:
    """Escape pipes and collapse newlines for Markdown table cells."""
    return value.replace("|", "\\|").replace("\n", " ").strip()


def _render_value(value: str) -> str:
    """Render a yes/no/partial cell."""
    return VALUE_DISPLAY[value]


def _evidence_link(evidence: str) -> str:
    """Render an evidence cell. If it looks like a URL, wrap as a Markdown link."""
    if not evidence:
        return ""
    if evidence.startswith("http://") or evidence.startswith("https://"):
        return f"[link]({evidence})"
    # Path-style citation like `README.md#anchor` or `docs/journal-schema.md`.
    return f"[{evidence}]({evidence})"


def _ordered_categories(rows: Iterable[Row]) -> list[str]:
    seen: list[str] = []
    for row in rows:
        if row.category not in seen:
            seen.append(row.category)
    ordered = [c for c in CATEGORY_ORDER if c in seen]
    extras = [c for c in seen if c not in CATEGORY_ORDER]
    return ordered + extras


def render_headline_table(rows: list[Row]) -> str:
    """Short README headline table — only rows flagged `headline: true`."""
    headline_rows = [r for r in rows if r.headline]
    if not headline_rows:
        return "_No headline features defined._\n"

    lines = [
        "| Feature | zccache | sccache |",
        "|---|:---:|:---:|",
    ]
    for row in headline_rows:
        lines.append(
            "| {feature} | {z} | {s} |".format(
                feature=_escape_cell(row.feature),
                z=_render_value(row.zccache),
                s=_render_value(row.sccache),
            )
        )
    return "\n".join(lines) + "\n"


def render_full_readme_table(rows: list[Row]) -> str:
    """Full README table (inside the <details> block). No notes/evidence columns —
    those live in docs/FEATURE-MATRIX.md to keep the README dropdown scannable."""
    out: list[str] = []
    for category in _ordered_categories(rows):
        out.append(f"#### {category}")
        out.append("")
        out.append("| Feature | zccache | sccache |")
        out.append("|---|:---:|:---:|")
        for row in rows:
            if row.category != category:
                continue
            out.append(
                "| {feature} | {z} | {s} |".format(
                    feature=_escape_cell(row.feature),
                    z=_render_value(row.zccache),
                    s=_render_value(row.sccache),
                )
            )
        out.append("")
    return "\n".join(out)


def render_feature_matrix_md(rows: list[Row]) -> str:
    """Canonical long-form view at docs/FEATURE-MATRIX.md."""
    header = [
        "# Feature comparison: zccache vs sccache",
        "",
        GENERATED_BANNER,
        "",
        "This document is generated from `docs/feature-matrix.yaml` by "
        "`ci/render_feature_matrix.py`. To change a row, edit the YAML and "
        "re-run the renderer (`uv run --with pyyaml python "
        "ci/render_feature_matrix.py`). CI fails if this file is stale.",
        "",
        "sccache claims are best-effort and sourced from the upstream README "
        "and docs at <https://github.com/mozilla/sccache>. When uncertain, a "
        "row is marked `partial` with a note rather than `no`.",
        "",
    ]
    out = list(header)
    for category in _ordered_categories(rows):
        out.append(f"## {category}")
        out.append("")
        out.append("| Feature | zccache | sccache | Notes | Evidence |")
        out.append("|---|:---:|:---:|---|---|")
        for row in rows:
            if row.category != category:
                continue
            out.append(
                "| {feature} | {z} | {s} | {notes} | {evidence} |".format(
                    feature=_escape_cell(row.feature),
                    z=_render_value(row.zccache),
                    s=_render_value(row.sccache),
                    notes=_escape_cell(row.notes),
                    evidence=_evidence_link(row.evidence),
                )
            )
        out.append("")
    return "\n".join(out)


# ---------------------------------------------------------------------------
# README marker rewriting
# ---------------------------------------------------------------------------


def _replace_between_markers(text: str, begin: str, end: str, body: str) -> str:
    """Replace the region between marker lines with `body`.

    Markers themselves are preserved. `body` must NOT include the markers.
    A single newline separates each marker from the body to keep the diff
    clean and idempotent across reruns.
    """
    pattern = re.compile(
        r"(" + re.escape(begin) + r")(.*?)(" + re.escape(end) + r")",
        re.DOTALL,
    )
    if not pattern.search(text):
        raise SystemExit(
            f"README markers not found: {begin} / {end}. "
            "Add the marker pair to README.md before running the renderer."
        )
    replacement = begin + "\n" + body.rstrip() + "\n" + end
    return pattern.sub(lambda _: replacement, text, count=1)


def render_readme(existing_readme: str, rows: list[Row]) -> str:
    headline_body = render_headline_table(rows)
    full_body = render_full_readme_table(rows)
    updated = _replace_between_markers(existing_readme, HEADLINE_BEGIN, HEADLINE_END, headline_body)
    updated = _replace_between_markers(updated, FULL_BEGIN, FULL_END, full_body)
    return updated


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def _write_if_changed(path: Path, content: str) -> bool:
    """Write content to path. Returns True if the file was changed."""
    current = path.read_text(encoding="utf-8") if path.exists() else ""
    if current == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def _compare(path: Path, rendered: str) -> bool:
    """Return True if path matches rendered content."""
    if not path.exists():
        return False
    return path.read_text(encoding="utf-8") == rendered


def main(argv: list[str] | None = None) -> int:
    doc = __doc__ or ""
    parser = argparse.ArgumentParser(description=doc.split("\n\n", 1)[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify rendered outputs match the YAML. Exit non-zero if stale.",
    )
    args = parser.parse_args(argv)

    rows = load_rows(YAML_PATH)

    existing_readme = README_PATH.read_text(encoding="utf-8")
    rendered_readme = render_readme(existing_readme, rows)
    rendered_matrix_md = render_feature_matrix_md(rows)

    if args.check:
        stale: list[Path] = []
        if existing_readme != rendered_readme:
            stale.append(README_PATH)
        if not _compare(FEATURE_MATRIX_PATH, rendered_matrix_md):
            stale.append(FEATURE_MATRIX_PATH)

        if stale:
            sys.stderr.write(
                "feature-matrix is stale relative to docs/feature-matrix.yaml:\n"
            )
            for path in stale:
                sys.stderr.write(f"  - {path.relative_to(REPO_ROOT)}\n")
            sys.stderr.write(
                "\nRun:\n"
                "  uv run --with pyyaml python ci/render_feature_matrix.py\n"
                "and commit the result.\n"
            )
            return 1
        print("feature-matrix: up to date")
        return 0

    changed: list[Path] = []
    if _write_if_changed(README_PATH, rendered_readme):
        changed.append(README_PATH)
    if _write_if_changed(FEATURE_MATRIX_PATH, rendered_matrix_md):
        changed.append(FEATURE_MATRIX_PATH)

    if changed:
        for path in changed:
            print(f"updated {path.relative_to(REPO_ROOT)}")
    else:
        print("feature-matrix: no changes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
