"""Set up project-local sccache directory versioned by rustc toolchain.

Creates .sccache/<version>-<commit_hash>/ so different compiler versions
never share cached artifacts. Writes .cargo/config.toml so cargo picks up
RUSTC_WRAPPER and SCCACHE_DIR automatically.

Exit codes:
  0 - Success or graceful skip (sccache/rustc not found)
"""

import subprocess
import sys
from pathlib import Path

from ci.env import clean_env, ensure_windows_msvc, require_tool_path

PROJECT_ROOT = Path(__file__).parent.parent.resolve()
SCCACHE_BASE = PROJECT_ROOT / ".sccache"
CARGO_CONFIG = PROJECT_ROOT / ".cargo" / "config.toml"


def get_rustc_verbose():
    """Get `rustc --version --verbose` output via the rustup toolchain."""
    rustc = require_tool_path("rustc")
    result = subprocess.run(
        [str(rustc), "--version", "--verbose"],
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        env=clean_env(),
    )
    if result.returncode != 0:
        return None
    return result.stdout.strip()


def parse_cache_dir_name(verbose_output):
    """Extract 'release-commit[:8]' from verbose output."""
    version = None
    commit = None
    for line in verbose_output.splitlines():
        if line.startswith("release:"):
            version = line.split(":", 1)[1].strip()
        elif line.startswith("commit-hash:"):
            commit = line.split(":", 1)[1].strip()[:8]
    if version and commit:
        return f"{version}-{commit}"
    return None


def write_cargo_config(cache_dir):
    """Write .cargo/config.toml with sccache wrapper and cache dir."""
    # Use forward slashes for TOML compatibility
    cache_dir_str = str(cache_dir).replace("\\", "/")

    content = f"""\
# Auto-generated by ci/sccache_setup.py — do not edit manually.
# Versioned sccache directory ensures compiler upgrades get a fresh cache.

[build]
rustc-wrapper = "sccache"

[env]
SCCACHE_DIR = "{cache_dir_str}"
"""
    CARGO_CONFIG.parent.mkdir(parents=True, exist_ok=True)
    CARGO_CONFIG.write_text(content, encoding="utf-8")


def main():
    try:
        ensure_windows_msvc()
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    # Check sccache is installed
    try:
        subprocess.run(
            ["sccache", "--version"],
            capture_output=True,
            check=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        return 0  # silently skip

    verbose = get_rustc_verbose()
    if verbose is None:
        return 0

    dir_name = parse_cache_dir_name(verbose)
    if dir_name is None:
        return 0

    cache_dir = SCCACHE_BASE / dir_name
    cache_dir.mkdir(parents=True, exist_ok=True)

    # Check if config already points here — skip rewrite if unchanged
    cache_dir_fwd = str(cache_dir).replace("\\", "/")
    if CARGO_CONFIG.exists():
        content = CARGO_CONFIG.read_text(encoding="utf-8")
        if cache_dir_fwd in content:
            return 0

    # Stop sccache server so it picks up new SCCACHE_DIR on next invocation
    subprocess.run(["sccache", "--stop-server"], capture_output=True)

    write_cargo_config(cache_dir)
    print(f"sccache: {cache_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
