name: Windows

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "LICENSE*"
      - "NOTICE*"
      - "AUTHORS*"
      - "CODEOWNERS"
      - "CONTRIBUTING*"
      - ".gitignore"
      - ".gitattributes"
      - ".editorconfig"
      - "tasks/**"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "LICENSE*"
      - "NOTICE*"
      - "AUTHORS*"
      - "CODEOWNERS"
      - "CONTRIBUTING*"
      - ".gitignore"
      - ".gitattributes"
      - ".editorconfig"
      - "tasks/**"

jobs:
  windows:
    uses: ./.github/workflows/ci-check.yml
    with:
      os: windows-latest
